### PR TITLE
Adding addon-test-support to ember-scroll-modifiers

### PR DESCRIPTION
**Pull request by ygongdev**
This new helper will support most of the API that the consumer should care about, `onEnter`, `onExit`, `maxEnter`, and `maxExit`.

**Description**
- [x] Adds a new `addon-test-support` helper, `did-intersect-mock`
- [x] Added a few integration tests for `did-intersect-mock` to make sure it'll work.
- [ ] Documentation, will add after initial review looks good.

**API**
 - [x] enter - mimics `onEnter`, but since it is directly invokable, `enter` sounds more semantic.
 - [x] exit - mimics `onExit`, name follows same reason.

### CODE REVIEW

**Comment by elwayman02** [comment]
At the risk of taking this in an entirely different direction - What do you think of the idea @pzuraq raised on Slack earlier? Instead of mocking it this way, can we avoid mocking the modifier itself altogether and instead just mock `IntersectionObserver`? Then, the interface we expose to consumers can still have an API like you proposed where the naming is around `enter` and `exit`, but under the hood all we're doing is manually triggering callbacks from our mock `IntersectionObserver` and letting the actual modifier function normally? This would have the added bonus of being testable within our existing test suite, because we'd basically replace the current mocked IO with the util you're building here.

**Comment by ygongdev** [comment]
We can explore that in a separate PR, just wanted to put this one up to gauge interest.

**Comment by elwayman02** [comment]
I think if we took that approach, we wouldn't need this PR at all. That's why I wanted to bring it up now, because going the direction of the IO Mock would eliminate the need for mocking the modifier entirely.

**Comment by elwayman02** [comment]
That is, `DidIntersectMock` would just have two methods - `enter()` and `exit()`, and calling those methods would trigger the IO mock under the hood. I don't think we'd need anything else, right?

**Comment by ygongdev** [comment]
I don't know if we can 100% replace the tests, but here's one with IO mock #306

**Comment by ygongdev** [comment]
Closing in favor of #306

**Pull request closed without merging**
